// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UserInterface interface {
	IsUserInterface()
	GetUsername() string
	GetPassword() string
	GetQuestion() string
	GetAnswer() string
}

type SignUpInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type UserCredentials struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	Password string `json:"password"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

func (UserCredentials) IsUserInterface()         {}
func (this UserCredentials) GetUsername() string { return this.Username }
func (this UserCredentials) GetPassword() string { return this.Password }
func (this UserCredentials) GetQuestion() string { return this.Question }
func (this UserCredentials) GetAnswer() string   { return this.Answer }
