// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangePasswordByAnswerInput struct {
	Change *ChangePasswordInput `json:"change"`
	Answer string               `json:"answer"`
}

type ChangePasswordInput struct {
	Password string `json:"password"`
}

type GetUserByIDInput struct {
	UserID string `json:"userId"`
}

type GetUserByUsernameInput struct {
	Username string `json:"username"`
}

type SignInInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignUpInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type Tokens struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type UserAuthResponse struct {
	Tokens *Tokens `json:"tokens"`
	UserID string  `json:"userId"`
}

type UserQuestionResponse struct {
	Auth     *UserAuthResponse `json:"auth"`
	Question string            `json:"question"`
}

type UserResponse struct {
	Auth     *UserAuthResponse `json:"auth"`
	Username string            `json:"username"`
}
