// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SignUpInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type Tokens struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type UserAuthResponse struct {
	Tokens *Tokens `json:"tokens"`
	UserID string  `json:"userId"`
}

type UserCredentials struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	Password string `json:"password"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}
