package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/dehwyy/Makoto/backend/distributor/graphql/model"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input *model.SignUpInput) (string, error) {
	fmt.Println(input.Username)
	return input.Username, nil
}

// GetQuestion is the resolver for the getQuestion field.
func (r *queryResolver) GetQuestion(ctx context.Context, username string) (string, error) {
	panic(fmt.Errorf("not implemented: GetQuestion - getQuestion"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
