package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/dehwyy/Makoto/backend/distributor/graphql/model"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUpInput) (*model.UserAuthResponse, error) {
	panic(fmt.Errorf("not implemented: SignUp - signUp"))
}

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, input model.SignInInput) (*model.UserAuthResponse, error) {
	panic(fmt.Errorf("not implemented: SignIn - signIn"))
}

// SignOut is the resolver for the signOut field.
func (r *mutationResolver) SignOut(ctx context.Context) (*model.Status, error) {
	panic(fmt.Errorf("not implemented: SignOut - signOut"))
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (*model.UserAuthResponse, error) {
	panic(fmt.Errorf("not implemented: ChangePassword - changePassword"))
}

// ChangePasswordByAnswer is the resolver for the changePasswordByAnswer field.
func (r *mutationResolver) ChangePasswordByAnswer(ctx context.Context, input model.ChangePasswordByAnswerInput) (*model.UserAuthResponse, error) {
	panic(fmt.Errorf("not implemented: ChangePasswordByAnswer - changePasswordByAnswer"))
}

// CreateWord is the resolver for the createWord field.
func (r *mutationResolver) CreateWord(ctx context.Context, word model.Word) (*model.Tokens, error) {
	panic(fmt.Errorf("not implemented: CreateWord - createWord"))
}

// RemoveWord is the resolver for the RemoveWord field.
func (r *mutationResolver) RemoveWord(ctx context.Context, wordID string) (*model.Tokens, error) {
	panic(fmt.Errorf("not implemented: RemoveWord - RemoveWord"))
}

// EditWord is the resolver for the EditWord field.
func (r *mutationResolver) EditWord(ctx context.Context, input *model.EditWordInput) (*model.Tokens, error) {
	panic(fmt.Errorf("not implemented: EditWord - EditWord"))
}

// GetUserByUsername is the resolver for the getUserByUsername field.
func (r *queryResolver) GetUserByUsername(ctx context.Context, input model.GetUserByUsernameInput) (*model.UserResponse, error) {
	panic(fmt.Errorf("not implemented: GetUserByUsername - getUserByUsername"))
}

// GetUserByID is the resolver for the getUserById field.
func (r *queryResolver) GetUserByID(ctx context.Context, input model.GetUserByIDInput) (*model.UserResponse, error) {
	panic(fmt.Errorf("not implemented: GetUserByID - getUserById"))
}

// GetQuestion is the resolver for the getQuestion field.
func (r *queryResolver) GetQuestion(ctx context.Context) (*model.UserQuestionResponse, error) {
	panic(fmt.Errorf("not implemented: GetQuestion - getQuestion"))
}

// GetWords is the resolver for the getWords field.
func (r *queryResolver) GetWords(ctx context.Context, userID *string) (*model.GetWordsResponse, error) {
	panic(fmt.Errorf("not implemented: GetWords - getWords"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) GetUser(ctx context.Context, username string) (*model.UserResponse, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}
