services:
  twirp_gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/twirp/Dockerfile
    ports:
      - ${TWIRP_GATEWAY_PORT}:80
    container_name: twirp_gateway
    env_file:
      - .env.prod
    networks:
      - makoto_network

  # auth:
  #   build:
  #     context: .
  #     dockerfile: ./apps/auth/Dockerfile
  #   ports:
  #     - ${AUTH_PORT}:80
  #   container_name: auth
  #   env_file:
  #     - .env.prod
  #   depends_on:
  #     - db
  #   networks:
  #     - makoto_network
  #     - makoto_db

  db:
    restart: always
    image: postgres:latest
    container_name: makoto_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    networks:
      - makoto_db

networks:
  makoto_network:
    external: true
  makoto_db:
    name: makoto_db
