//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::languages::Entity as Languages;
pub use super::user_infos::Entity as UserInfos;
pub use super::users_languages::Entity as UsersLanguages;
