//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub access_token: Option<Vec<String>>,
    #[sea_orm(column_type = "Text")]
    pub refresh_token: String,
    pub expiry: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_credentials::Entity",
        from = "Column::UserId",
        to = "super::user_credentials::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserCredentials,
}

impl Related<super::user_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCredentials.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
