ports:
  gateway: <string>
  auth: <string>
frontend_ports:
  auth: <string>
databases:
  auth: <postgres dsn>
oauth2:
  google:
    client_id: <OAuth2 client id>
    secret: <OAuth2 client secret>
    redirect_url: <full_url>
