ui:
	bunx shadcn-ui@latest add  accordion alert-dialog button calendar command context-menu dialog dropdown-menu menubar navigation-menu popover scroll-area select separator sheet skeleton switch table tabs toast
