name: Go Tests

on:
  push:
    branches:
      - v2
      - dev

env:
  WORKFLOW: true

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Install Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable


      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Install protoc plugins
        run: go install github.com/twitchtv/twirp/protoc-gen-twirp@latest && go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1 && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

      - name: Run Task compile twirp
        run: task protoc-twirp-go
      - name: Run Task compile grpc
        run: task grpc-go

      - name: Run tests
        run: task go-test
